classroom/classroom/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from users import views as user_views
from resource import views as res_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', user_views.home , name = 'home'),
    path('userfp/', res_views.userhome , name = 'userhome'),
    path('favourite/', res_views.bookmarked , name = 'favourite'),
    path('search/', res_views.search , name = 'search'),
    path('addtopic/', res_views.newTopic , name = 'addtopic'),
    path('like/<int:pk>', res_views.likeview , name = 'like_post'),
    path('fav/<int:pk>', res_views.favview , name = 'fav_post'),
    path('<int:user_id>/user/', user_views.diffprofile , name = 'userop'),
    path('<int:topic_id>/addmaterial/', res_views.newMaterial, name='addmaterial'),
    path('github/', res_views.github , name = 'git'),
    path('cf/', res_views.codef , name = 'cf'),
    path('<int:topic_id>/detail/', res_views.detail, name='detail'),
    path('accounts/', include('allauth.urls')),
    path('register/', user_views.register , name = 'register'),
    path('profile/', user_views.profile, name='profile'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name="reset_password"),

    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name="password_reset_done"),

    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name="password_reset_confirm"),

    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name="password_reset_complete"),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

classroom/resource/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.

class Topic(models.Model):
	name = models.CharField(max_length=500,null=False,blank=False)
	created = models.DateTimeField('date created', default = timezone.now)
	last_updated = models.DateTimeField('last updated', default = timezone.now)
	user =  models.ForeignKey(User,on_delete=models.PROTECT)

	def __str__(self):
		return self.name


class Material(models.Model):
	url = models.URLField(null = False)
	topic = models.ForeignKey(Topic,on_delete = models.CASCADE)
	desc =  models.TextField(max_length=500,default = 'None')
	created = models.DateTimeField('date created',default = timezone.now)
	last_updated = models.DateTimeField('last updated',default = timezone.now)
	user = models.ForeignKey(User,on_delete = models.PROTECT)
	likes = models.ManyToManyField(User, related_name = 'Material_op')
	fav = models.ManyToManyField(User,related_name='favorite')

	@property
	def total_likes(self):
		return self.likes.count()

	def __str__(self):
		return self.url

classroom/resource/templates/resource/addmaterial.html
{% extends "users/home.html" %}
{% load socialaccount %}
{% providers_media_js %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    	<form method="POST">
    		{% csrf_token %}
    		<fieldset class="form-group">
    			<legend class="border-bottom mb-4">Add New Resource</legend>
    			{{ form|crispy }}
    			
    		</fieldset>
    		<div class="form-group">
    			<button class ="btn btn-outline-info" type ="Submit">Submit</button>
    		</div>
    	</form>
        
    </div>
{% endblock content %}

classroom/resource/templates/resource/addtopic.html
{% extends "users/home.html" %}
{% load socialaccount %}
{% providers_media_js %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    	<form method="POST">
    		{% csrf_token %}
    		<fieldset class="form-group">
    			<legend class="border-bottom mb-4">Add New Topic</legend>
    			{{ form|crispy }}
    			
    		</fieldset>
    		<div class="form-group">
    			<button class ="btn btn-outline-info" type ="Submit">Submit</button>
    		</div>
    	</form>
        
    </div>
{% endblock content %}

classroom/resource/templates/resource/cf.html
{% extends "users/home.html" %}
{% block content %}
  <h2>Codeforces API</h2>
  <form method="get">
    <input type="text" name="username">
    <button type="submit">search </button>
  </form>
  {% if user %}
  	<marquee>{{ user.result.0.rank }}</marquee> 
  {% endif %}	
  
{% endblock content %}

classroom/resource/templates/resource/detail.html
{% extends "users/home.html" %}
{% block content %}
  <h1>{{ topic.name }}</h1>
  <a href="{% url 'addmaterial' topic.id %}">Add Resource</a>
  <br>
  {% if topic.material_set.count == 0 %}
    <div>
       <strong>Oooops!</strong> There are no resources for this topic. Be the first to add one.
    </div>

  {% else %}
    {% for material in topic.material_set.all %}
        <article class="media content-section"> 
          <div class="media-body">
            <div class="article-metadata">User: 
              <a class="mr-2" href="{% url 'userop' material.user.id %}">{{ material.user }}</a>
            </div>
            <a class="article-title" href="{{ material.url }}">{{ material.url | truncatechars:20}}</a> 
            <p><small class="text-muted">{{ material.desc }}</small></p>
          
            <form action ="{% url 'like_post' material.id %}" method="POST" >
            {% csrf_token %}
            <button type="submit" , name="post_id",value ="{{ material.id }}" , class="btn btn-primary btn-sm">Like {{ material.total_likes }} </button>
          </form>
          
          </div>
          <form action ="{% url 'fav_post' material.id %}" method="POST" >
            {% csrf_token %}
            <button type="submit" , name="post_id",value ="{{ material.id }}" , class="btn btn-primary btn-sm">Fav</button>
          </form>
          
        </article>
    {% endfor %}
  {% endif %} 


{% endblock content %}

classroom/resource/templates/resource/favourite.html
{% extends "users/home.html" %}
{% block content %}
  <h1>Fav</h1>
  <br>
    {% for material in fav_res %}
        <article class="media content-section"> 
          <div class="media-body">
            <div class="article-metadata">Topic: 
              <a class="mr-2" href="{% url 'detail' material.topic.id %}">{{ material.topic }}</a>
            </div>
            <a class="article-title" href="{{ material.url }}">{{ material.url | truncatechars:20}}</a> 
            <p><small class="text-muted">{{ material.desc }}</small></p>
          </div>
        </article>
    {% endfor %}
{% endblock content %}

classroom/resource/templates/resource/github.html
{% extends "users/home.html" %}
{% block content %}
    <h2>GitHub API</h2>
  <form method="get">
    <input type="text" name="username">
    <button type="submit">search on github</button>
  </form>
  {% if user %}
    <p><strong>{{ user.name }}</strong> has <strong>{{ user.public_repos }}</strong> public repositories.</p>
    <p><marquee>{{ user.bio }}</marquee></p>
  {% endif %}
{% endblock content %}

classroom/resource/templates/resource/search.html
{% extends "users/home.html" %}
{% block content %}
	<form method="get">
    <input type="text" name="qname">
    <button type="submit">search </button>
  </form>
    <h1>Search Result:</h1>
    {% for top in topic %}
    	<h3>{{ top.name }}</h3>
    {% endfor %}
{% endblock content %}

classroom/resource/templates/resource/userhome.html
{% extends "users/home.html" %}
{% block content %}
  <form method="get">
    <input type="text" name="qname">
    <button type="submit">search </button>
  </form>
    {% if topicop %}
    <h1>Search Result:</h1>
    {% endif %}
    {% for topic in topicop %}
      <article class="media content-section">
          <div class="media-body">
            <h3><a class="article-title" href="{% url 'detail' topic.id %}">{{ topic.name }}</a></h3>
          </div>
          <h3>{{ topic.Material_count }}</h3>
        </article>
    {% endfor %}
    <h1>Topics:</h1>
    {% for topic in topic %}
        <article class="media content-section">
          <div class="media-body">
            <h3><a class="article-title" href="{% url 'detail' topic.id %}">{{ topic.name }}</a></h3>
          </div>
          <h3>{{ topic.Material_count }}</h3>
        </article>
    {% endfor %}
{% endblock content %}